### PR TITLE
Create Unicode versions of the files

### PR DESCRIPTION
**Pull request by mrgreekgeek**
@normansimonr here's a request to update the Stephens text to also have Unicode files available.

### CODE REVIEW

**Comment by mrgreekgeek** [comment]
@normansimonr I just realized that `MT.STV` is different, and has some extra newlines (which leaves an extraneous newline in the resultant Unicode file). Should the file be fixed, or shall I adjust my script to compensate?

**Comment by normansimonr** [comment]
Hi @mrgreekgeek thanks so much for this contribution! I will probably have some time to review it in one or two weeks, but to answer your question, we can't change the source files unless requested by Professor Robinson, so adjusting the script would the the best course of action. Thanks!

**Comment by mrgreekgeek** [comment]
It's a pleasure, @normansimonr! I just updated the script with a few little tweaks. Do I need to re-upload the resultant unicode files as well, or will you be re-generating them anyway?

**Comment by normansimonr** [comment]
@mrgreekgeek Brilliant, thank you so much! Yes, please, commit the Unicode files as well. That way I can verify both your script and the output.

Thanks!

**Comment by mrgreekgeek** [comment]
@normansimonr My pleasure! I've updated the files.

**Comment by normansimonr** [comment]
I've checked the generated files and in general they seem to have been converted correctly. I wasn't able to detect any systematic conversion errors to the best of my ability.

Thank you very much @mrgreekgeek for this great contribution!

**Pull request merged**
